# Ensure that there is a 1:1 mapping of cinder-volume
# backend configmap to its corresponding cinder-volume pod

- include: backends/iscsi.yml
  when: result.conf_dict['cinder_enable_iscsi_backend']
- include: backends/ceph.yml
  when: result.conf_dict['cinder_enable_rbd_backend']
- include: backends/xtremio.yml
  when: result.conf_dict['dellemc_xtremio_iscsi_backend']
