# Gather list of enabled backends here
- name: Append backend to enable_backends list
  set_fact:
    enabled_backends: "{{ enabled_backends }} + [ 'tripleo_ceph' ]"
  when: result.conf_dict['cinder_enable_rbd_backend']

- name: Append backend to enable_backends list
  set_fact:
    enabled_backends: "{{ enabled_backends }} + [ 'tripleo_iscsi' ]"
  when: result.conf_dict['cinder_enable_iscsi_backend']

- name: Append backend to enable_backends list
  set_fact:
    enabled_backends: "{{ enabled_backends }} + [ 'xtremio' ]"
  when: result.conf_dict['dellemc_xtremio_iscsi_backend']

- name: Append backend to enable_backends list
  set_fact:
    enabled_backends: "{{ enabled_backends }} + [ 'tripleo_netapp' ]"
  when: result.conf_dict['cinder_enable_netapp_backend']

