- name: Translate hieradata
  include_role:
    name: 'ansible-role-k8s-tripleo'
  vars:
    schema:
      cinder::auth_strategy: DEFAULT.auth_strategy
      cinder::api::bind_port: bind_port
      cinder::rabbit_userid: oslo_messaging_rabbit.rabbit_userid
      cinder::rabbit_port: oslo_messaging_rabbit.rabbit_port
      cinder::rabbit_password: oslo_messaging_rabbit.rabbit_password
      cinder::rabbit_use_ssl: oslo_messaging_rabbit.rabbit_use_ssl
      cinder::rabbit_host: oslo_messaging_rabbit.rabbit_host
      cinder::rabbit_heartbeat_timeout_threshold: oslo_messaging_rabbit.rabbit_heartbeat_timeout_threshold
      cinder::glance::glance_api_servers: DEFAULT.glance_api_servers
      cinder::glance::glance_api_version: DEFAULT.glance_api_version
      cinder::database_connection: database.connection
      cinder::db::database_max_retries: database.max_retries
      cinder::db::database_db_max_retries: database.db_max_retries
      cinder::db::mysql::dbname: database.dbname
      cinder::db::mysql::host: database.host
      cinder::db::mysql::password: database.password
      cinder::db::mysql::user: database.user

      tripleo::profile::base::cinder::volume::cinder_enable_iscsi_backend: cinder_enable_iscsi_backend
      tripleo::profile::base::cinder::volume::cinder_enable_nfs_backend: cinder_enable_nfs_backend
      tripleo::profile::base::cinder::volume::cinder_enable_rbd_backend: cinder_enable_rbd_backend
      tripleo::profile::base::cinder::volume::nfs::cinder_nfs_mount_options: cinder_nfs_mount_options
      tripleo::profile::base::cinder::volume::nfs::cinder_nfs_servers: cinder_nfs_servers
      tripleo::profile::base::cinder::volume::nfs::cinder_nas_secure_file_operations: cinder_nas_secure_file_operations
      tripleo::profile::base::cinder::volume::nfs::cinder_nas_secure_file_permissions: cinder_nas_secure_file_permissions
      tripleo::profile::base::cinder::volume::iscsi::cinder_lvm_loop_device_size: cinder_lvm_loop_device_size
      tripleo::profile::base::cinder::volume::iscsi::cinder_iscsi_helper: cinder_iscsi_helper
      tripleo::profile::base::cinder::volume::iscsi::cinder_iscsi_protocol: cinder_iscsi_protocol
      tripleo::profile::base::cinder::volume::iscsi::cinder_iscsi_address: cinder_iscsi_address
      tripleo::profile::base::cinder::volume::rbd::cinder_rbd_pool_name: cinder_rbd_pool_name
      tripleo::profile::base::cinder::volume::rbd::cinder_rbd_user_name: cinder_rbd_user_name

      tripleo::profile::base::cinder::volume::dellemc_xtremio_iscsi_backend: dellemc_xtremio_iscsi_backend
      cinder::backend::dellemc_xtremio_iscsi::max_over_subscription_ratio: xtremio.max_over_subscription_ratio
      cinder::backend::dellemc_xtremio_iscsi::use_multipath_for_image_xfer: xtremio.use_multipath_for_image_xfer
      cinder::backend::dellemc_xtremio_iscsi::volume_backend_name: xtremio.volume_backend_name
      cinder::backend::dellemc_xtremio_iscsi::san_ip: xtremio.san_ip
      cinder::backend::dellemc_xtremio_iscsi::xtremio_cluster_name: xtremio.xtremio_cluster_name
      cinder::backend::dellemc_xtremio_iscsi::san_login: xtremio.san_login
      cinder::backend::dellemc_xtremio_iscsi::san_password: xtremio.san_password
      cinder::backend::dellemc_xtremio_iscsi::image_volume_cache_enabled: xtremio.image_volume_cache_enabled

      tripleo::profile::base::ceph::ceph_mon_host: ceph_mon_host
      ceph::profile::params::fsid: ceph_cluster_fsid
      ceph::profile::params::authentication_type: authentication_type

    default: '{{cinder_config}}'
    fact_variable: 'cinder_config'

