- name: Create cinder-volume-xtremio configmaps
  ignore_errors: yes
  k8s_v1_config_map:
    name: cinder-volume-xtremio
    namespace: "{{ namespace }}"
    state: present
    debug: yes
    labels:
      service: cinder-volume-xtremio
    data:
      config.json: |
        {
            "command": "/usr/bin/cinder-volume --config-file /usr/share/cinder/cinder-dist.conf --config-file /etc/cinder/cinder.conf",
            "config_files": [
                {
                    "source": "/var/lib/kolla/config_files/cinder.conf",
                    "dest": "/etc/cinder/cinder.conf",
                    "owner": "cinder",
                    "perm": "0600"
                }
            ],
            "permissions": [
                {
                    "path": "/var/lib/cinder",
                    "owner": "cinder:cinder",
                    "recurse": true
                },
                {
                    "path": "/var/log/kolla/cinder",
                    "owner": "cinder:cinder",
                    "recurse": true
                }
            ]
        }

      cinder.conf: |
        {{cinder_conf['content'] | b64decode}}

- name: Create Cinder Volume Deployment
  k8s_apps_v1beta1_deployment:
    name: cinder-volume-xtremio
    namespace: "{{ namespace }}"
    service_account_name: "{{ service_account }}"
    labels:
      app: cinder-volume-xtremio
      service: cinder-volume-xtremio
    replicas: 1
    spec_template_metadata_labels:
      app: cinder-volume-xtremio
      service: cinder-volume-xtremio
    containers:
    - name: cinder-volume
      image: tripleoupstream/centos-binary-cinder-volume:latest
      volumeMounts:
        - name: kolla-config
          mountPath: /var/lib/kolla/config_files/
      env:
        - name: TZ
          value: UTC
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
        - name: KOLLA_KUBERNETES
          value: ""
    volumes:
      - name: kolla-config
        config_map:
          name: cinder-volume-xtremio

